LobbyIP: 'lo.7mi.site'
LobbyBEIP: 'lobby.7mi.site (ポート(Port) 19134)'

DiscordToken: 'token'
DiscordGuildId: '810725404545515561'

DiscordVerifyUserRoleID: '810744661366407219'
DiscordVerifyCategoryID: '922217386013233242'

MySQLServer: 'mysql'
MySQLPort: 3306
MySQLDatabase: ''
MySQLOption: '?allowPublicKeyRetrieval=true&useSSL=false'
MySQLUsername: ''
MySQLPassword: ''